/*
Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

const isEven = (num) => num % 2 == 0

const fibonacci = (sum, prev, curr, limit) => {
    const nextTerm = prev + curr;
    const finalSum = isEven(curr) ? sum + curr : sum
    if (nextTerm >= limit) return finalSum;
    return fibonacci(finalSum, curr, nextTerm, limit);
}

const main = (maxLimit) => {
    return fibonacci(0, 1, 2, maxLimit)
}

console.log("Find the sum of the even-valued terms in fibonacci : " + main(4000000))

